### ISSUE TITLE
Button resolution placement

### ISSUE THREAD

**Issue by noahwaseaten** [noahwaseaten/website#8]
in order to access the new secretpage.html file you need to find and press the hidden button in friends.html, i set its position to the bottom right corner in full size window (firefox), but i noticed that when changing its window size or phone resolution it goes to somewhere completely random

I cant find a fix for it no matter how hard i searched, @PH4NT0MK please help (im going to focus on the mobile web version in the future, lets first fix the window size problem)

**Comment by PH4NT0MK** [comment]
![image](https://github.com/noahwaseaten/website/assets/139446704/22092793-c8b5-4e10-b2ae-d349f925310c)
'it works'

**Comment by PH4NT0MK** [comment]
It doesn't go somewhere random - it listens to the css. Does this issue still persist?
